"""add feature_requests and feature_cluster_labels

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-12 17:24:52.783943+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector eklentisini kur (yoksa oluştur, varsa atla)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_cluster_labels",
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("report_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_cluster_labels")),
    )
    op.create_index(
        op.f("ix_feature_cluster_labels_cluster_id"),
        "feature_cluster_labels",
        ["cluster_id"],
        unique=True,
    )
    op.create_table(
        "feature_requests",
        sa.Column("user_id", sa.String(length=60), nullable=False),
        sa.Column("request_raw", sa.Text(), nullable=False),
        sa.Column("request_embedded", Vector(768), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("fraud_score", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_feature_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_requests")),
    )
    op.create_index(
        op.f("ix_feature_requests_status"), "feature_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_feature_requests_user_id"),
        "feature_requests",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "challenge_types",
        "checklist",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Projenin kabul edilmesi için tamamlanması gereken adımlar (string listesi)",
        existing_nullable=True,
    )
    op.alter_column(
        "slack_users",
        "slack_joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Slack çalışma alanına katılım (UTC); API senkronunda doldurulur.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_users",
        "slack_joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Slack çalışma alanına katılım (UTC); API senkronunda doldurulur.",
        existing_nullable=True,
    )
    op.alter_column(
        "challenge_types",
        "checklist",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Projenin kabul edilmesi için tamamlanması gereken adımlar (string listesi)",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_feature_requests_user_id"), table_name="feature_requests")
    op.drop_index(op.f("ix_feature_requests_status"), table_name="feature_requests")
    op.drop_index(op.f("ix_feature_cluster_labels_cluster_id"), table_name="feature_cluster_labels")
    op.drop_table("feature_requests")
    op.drop_table("feature_cluster_labels")
    # ### end Alembic commands ###
